import { expect, test } from "@playwright/test"

test("Button selection animates corners with spatial tokens and respects reduced motion", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "no-preference" })
  await page.goto("/#/button")
  const button = page.locator('#button-selected button[data-size="default"][data-variant="default"]:not(:disabled)')
  await button.click()
  await expect(button).toHaveAttribute("aria-pressed", "false")
  await expect(button).toHaveCSS("border-radius", "12px")
  const transition = await button.evaluate(element => {
    element.click()
    return new Promise<{ duration: number; first: number; last: number }>(resolve => requestAnimationFrame(() => {
      getComputedStyle(element).borderTopLeftRadius
      const animation = element.getAnimations().find(animation => animation instanceof CSSTransition && animation.transitionProperty === "border-top-left-radius")!
      animation.pause()
      const duration = Number(animation.effect!.getTiming().duration)
      animation.currentTime = 0
      const first = parseFloat(getComputedStyle(element).borderTopLeftRadius)
      animation.currentTime = duration
      const last = parseFloat(getComputedStyle(element).borderTopLeftRadius)
      animation.finish()
      resolve({ duration, first, last })
    }))
  })
  expect(transition).toEqual({ duration: 350, first: 12, last: 20 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await button.click()
  await expect(button).toHaveAttribute("aria-pressed", "false")
  await expect(button).toHaveCSS("border-radius", "12px")
  expect(await button.evaluate(element => getComputedStyle(element).transitionDuration.split(",").every(duration => parseFloat(duration) <= 0.001))).toBe(true)
})

test("Button push uses spring timing with unchanged corners and stable layout", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "no-preference" })
  await page.goto("/#/button")
  const section = page.locator("#button-motion")
  const button = section.getByRole("button", { name: "Save a copy", exact: true }).last()
  await button.scrollIntoViewIfNeeded()
  const bounds = await button.boundingBox()
  const layout = await button.evaluate(element => [element.offsetWidth, element.offsetHeight])
  const style = await button.evaluate(element => {
    const css = getComputedStyle(element)
    return { properties: css.transitionProperty, speed: css.transitionDuration, curve: css.transitionTimingFunction }
  })
  expect(style.properties).not.toContain("all")
  expect(style.properties).not.toContain("transform")
  expect(style.properties).not.toContain("width")
  expect(style.speed).toBe("0.35s, 0.35s, 0.35s, 0.15s, 0.15s, 0.15s, 0.15s")
  expect(style.curve).toContain("cubic-bezier(0.42, 1.67, 0.21, 0.9)")
  expect(style.curve).toContain("cubic-bezier(0.31, 0.94, 0.34, 1)")
  await button.hover()
  await page.mouse.down()
  await expect.poll(() => button.evaluate(element => element.getAnimations().filter(animation => animation instanceof CSSTransition && animation.transitionProperty === "scale").length)).toBeGreaterThan(0)
  const samples = await button.evaluate(element => {
    const animations = element.getAnimations().filter(animation => animation instanceof CSSTransition && animation.transitionProperty === "scale")
    animations.forEach(animation => animation.pause())
    return [0, 0.2, 0.4, 0.6, 1].map(fraction => {
      animations.forEach(animation => { animation.currentTime = Number(animation.effect!.getTiming().duration) * fraction })
      return parseFloat(getComputedStyle(element).scale)
    })
  })
  expect(samples[0]).toBeCloseTo(1)
  expect(Math.min(...samples)).toBeLessThan(0.97)
  expect(samples.at(-1)).toBeCloseTo(0.97)
  expect(await button.evaluate(element => [element.offsetWidth, element.offsetHeight])).toEqual(layout)
  await expect(button).toHaveCSS("border-radius", "28px")
  await button.evaluate(element => element.getAnimations().forEach(animation => { if (animation.effect?.getTiming().iterations !== Infinity) animation.finish() }))
  await page.mouse.up()
  await expect(section.getByRole("status").last()).toHaveText("1 changes saved")
  await expect(button).toHaveCSS("scale", "none")
  await page.mouse.down()
  await page.mouse.up()
  await page.mouse.down()
  await page.mouse.up()
  await expect(section.getByRole("status").last()).toHaveText("3 changes saved")
  await expect(button).toHaveCSS("scale", "none")
  expect(await button.boundingBox()).toEqual(bounds)
  await button.focus()
  await page.keyboard.down("Space")
  await expect(button).toHaveCSS("scale", "0.97")
  await expect(button).toHaveCSS("translate", "0px 2px")
  await expect(button).toHaveCSS("border-radius", "28px")
  await page.keyboard.up("Space")
  await expect(section.getByRole("status").last()).toHaveText("4 changes saved")
  await expect(button).toHaveCSS("scale", "none")
  await page.evaluate(() => document.documentElement.style.setProperty("--button-spatial-speed", "600ms"))
  await expect(button).toHaveCSS("transition-duration", "0.6s, 0.6s, 0.6s, 0.15s, 0.15s, 0.15s, 0.15s")
  await page.evaluate(() => document.documentElement.style.removeProperty("--button-spatial-speed"))
})

test("Button reduced motion, joined corners, and touch activation retain their contracts", async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.goto("/#/button")
  const section = page.locator("#button-motion")
  const button = section.getByRole("button", { name: "Save a copy", exact: true }).last()
  await button.scrollIntoViewIfNeeded()
  const radius = await button.evaluate(element => getComputedStyle(element).borderRadius)
  await button.hover()
  await page.mouse.down()
  await expect(button).toHaveCSS("border-radius", radius)
  await expect(button).toHaveCSS("scale", "none")
  await expect(button).toHaveCSS("translate", "none")
  const durations = await button.evaluate(element => getComputedStyle(element).transitionDuration.split(",").map(value => parseFloat(value)))
  expect(durations.every(value => value <= 0.001)).toBeTruthy()
  await page.mouse.up()
  if (testInfo.project.name === "mobile") {
    await button.tap()
    await expect(section.getByRole("status").last()).toHaveText("2 changes saved")
  }
  const disabled = section.getByRole("button", { name: "Saving", exact: true }).last()
  await expect(disabled).toBeDisabled()
  await expect(disabled).toHaveCSS("border-radius", "28px")
  await page.emulateMedia({ reducedMotion: "no-preference" })
  await page.goto("/#/button-group")
  const grouped = page.locator('#button-group-default [data-slot="canvas"] [data-slot="button"]').first()
  await grouped.hover()
  const joined = await grouped.evaluate(element => getComputedStyle(element).borderRadius)
  await page.mouse.down()
  await expect(grouped).toHaveCSS("border-radius", joined)
  await expect(grouped).toHaveCSS("scale", "none")
  await page.mouse.up()
})

test("Button corner morph remains available only by explicit opt-in", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "no-preference" })
  await page.goto("/#/button")
  const button = page.locator('#button-motion [data-variant="secondary"][data-size="expressive"]')
  await button.evaluate(element => element.setAttribute("data-press-effect", "morph"))
  await button.hover()
  await page.mouse.down()
  await expect(button).toHaveCSS("border-radius", "12px")
  await expect(button).toHaveCSS("scale", "none")
  await expect(button).toHaveCSS("translate", "none")
  await page.mouse.up()
  await expect(button).toHaveCSS("border-radius", "28px")
})